CREATE TABLE IF NOT EXISTS swift_demo (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(64) NOT NULL DEFAULT '',
  create_time int(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
